// properties apartments, homes, condos, townhomes,

// apartments
const properties = [
  {
    id: '51',
    mlsId: '00051',
    realtorId: 'agent3',
    name: 'Rachel Chase',
    photo: '/images/realtors/agent1.jpg',
    title: 'Owner- Broker',
    phone: '701-555-5555',
    email: 'chaserachel@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    realtor: 'Dakota Realtors',
    propertyType: 'Apartments',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/apartments/apt1.jpg',
    image1: '/images/apartments/studio2.jpg',
    image2: '/images/apartments/studio3.jpg',
    image3: '/images/apartments/studio4.jpg',
    image4: '/images/apartments/gym1.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    price: '1,500 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 4,
    yearBuilt: 1981,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '53',
    mlsId: '00053',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    propertyType: 'Apartments',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/apartments/apt3.jpg',
    image1: '/images/livingroom/lr1.jpg',
    image2: '/images/bedrooms/bedroom3.jpg',
    image3: '/images/kitchen/kitchen1.jpg',
    image4: '/images/apartments/gym4.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    price: '1,100 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1988,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '56',
    mlsId: '00056',
    realtorId: 'agent3',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    propertyType: 'Apartments',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/apartments/apt6.jpg',
    image1: '/images/livingroom/lr4.jpg',
    image2: '/images/bedrooms/bedroom4.jpg',
    image3: '/images/kitchen/kitchen3.jpg',
    image4: '/images/bathrooms/bathroom6.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    price: '2,100 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2002,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '58',
    mlsId: '00058',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtos',
    propertyType: 'Apartments',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/apartments/apt8.jpg',
    image1: '/images/livingroom/lr6.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen5.jpg',
    image4: '/images/bathrooms/bathroom12.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '2 1/2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    price: '3,300 per/month',
    sqft: 2800,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '63',
    mlsId: '00063',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo1.jpg',
    image1: '/images/livingroom/lr1.jpg',
    image2: '/images/bedrooms/bedroom2.jpg',
    image3: '/images/kitchen/kitchen1.jpg',
    image4: '/images/bathrooms/bathroom2.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    rentOrBuy: 'For Rent',
    price: '1,600 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '66',
    mlsId: '00066',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/condos/condo4.jpg',
    image1: '/images/livingroom/lr4.jpg',
    image2: '/images/bedrooms/bedroom4.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom5.jpg',
    image5: '/images/apartments/gym4.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: 1,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,800 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },

  {
    id: '68',
    mlsId: '00068',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/condos/condo6.jpg',
    image1: '/images/livingroom/lr8.jpg',
    image2: '/images/bedrooms/bedroom8.jpg',
    image3: '/images/kitchen/kitchen7.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym4.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: 2,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '2,900 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '69',
    mlsId: '00069',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    rentOrBuy: 'For Rent',
    verified: 'Verified',
    image: '/images/condos/condo7.jpg',
    image1: '/images/livingroom/lr9.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen5.jpg',
    image4: '/images/bathrooms/bathroom7.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: 3,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '3,800 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
];

export default properties;
