// mls data apartments, condos, houses, townhomes,

const listings = [
  // apartments //
  {
    id: '51',
    mlsId: '00051',
    realtorId: 'agent3',
    name: 'Rachel Chase',
    photo: '/images/realtors/agent1.jpg',
    title: 'Owner- Broker',
    phone: '701-555-5555',
    email: 'chaserachel@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt1.jpg',
    image1: '/images/apartments/studio2.jpg',
    image2: '/images/apartments/studio3.jpg',
    image3: '/images/apartments/studio4.jpg',
    image4: '/images/apartments/gym1.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartments',
    price: '1,500 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 4,
    yearBuilt: 1981,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '52',
    mlsId: '00052',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt2.jpg',
    image1: '/images/apartments/studio5.jpg',
    image2: '/images/apartments/studio6.jpg',
    image3: '/images/apartments/studio7.jpg',
    image4: '/images/apartments/gym2.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '2,000 per/month',
    sqft: 1100,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1992,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '53',
    mlsId: '00053',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt3.jpg',
    image1: '/images/livingroom/lr1.jpg',
    image2: '/images/bedrooms/bedroom3.jpg',
    image3: '/images/kitchen/kitchen1.jpg',
    image4: '/images/apartments/gym4.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '1,100 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1988,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '54',
    mlsId: '00054',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt4.jpg',
    image1: '/images/livingroom/lr2.jpg',
    image2: '/images/bedrooms/bedroom4.jpg',
    image3: '/images/kitchen/kitchen2.jpg',
    image4: '/images/apartments/gym4.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '1,700 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1995,
    garageCapacity: 'Single',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '55',
    mlsId: '00055',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt5.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom3.jpg',
    image3: '/images/kitchen/kitchen3.jpg',
    image4: '/images/bathrooms/bathroom4.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '1,900 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1999,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '56',
    mlsId: '00056',
    realtorId: 'agent3',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt6.jpg',
    image1: '/images/livingroom/lr4.jpg',
    image2: '/images/bedrooms/bedroom4.jpg',
    image3: '/images/kitchen/kitchen3.jpg',
    image4: '/images/bathrooms/bathroom6.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '2,100 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2002,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '57',
    mlsId: '00057',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt7.jpg',
    image1: '/images/livingroom/lr5.jpg',
    image2: '/images/bedrooms/bedroom8.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '3,300 per/month',
    sqft: 2100,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2003,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '58',
    mlsId: '00058',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtos',
    verified: 'Verified',
    image: '/images/apartments/apt8.jpg',
    image1: '/images/livingroom/lr6.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen5.jpg',
    image4: '/images/bathrooms/bathroom12.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '2 1/2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '3,300 per/month',
    sqft: 2800,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '59',
    mlsId: '00059',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt9.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '3,300 per/month',
    sqft: 3300,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 1998,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '60',
    mlsId: '00060',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt10.jpg',
    image1: '/images/livingroom/lr8.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen7.jpg',
    image4: '/images/bathrooms/bathroom14.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    price: '5,000 per/month',
    propertyType: 'Apartment',
    sqft: 3300,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },

  {
    id: '61',
    mlsId: '00061',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Apartments',
    verified: 'Verified',
    image: '/images/apartments/apt11.jpg',
    image1: '/images/livingroom/lr9.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen8.jpg',
    image4: '/images/bathrooms/bathroom14.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '5,100 per/month',
    sqft: 3300,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },

  {
    id: '62',
    mlsId: '00062',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/apartments/apt12.jpg',
    image1: '/images/livingroom/lr8.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen9.jpg',
    image4: '/images/bathrooms/bathroom14.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury apartments in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Apartment',
    price: '5,400 per/month',
    sqft: 3300,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  // condos
  {
    id: '63',
    mlsId: '00063',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo1.jpg',
    image1: '/images/livingroom/lr1.jpg',
    image2: '/images/bedrooms/bedroom2.jpg',
    image3: '/images/kitchen/kitchen1.jpg',
    image4: '/images/bathrooms/bathroom2.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,500 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '64',
    mlsId: '00064',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo2.jpg',
    image1: '/images/livingroom/lr2.jpg',
    image2: '/images/bedrooms/bedroom2.jpg',
    image3: '/images/kitchen/kitchen2.jpg',
    image4: '/images/bathrooms/bathroom2.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: 'Studio',
    bathrooms: 1,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,300 per/month',
    sqft: 1100,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '65',
    mlsId: '00065',
    realtorId: 'agent4',
    name: 'James Johnson',
    photo: '/images/realtors/agent4.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'johnsonjames@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '3 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo3.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom3.jpg',
    image3: '/images/kitchen/kitchen3.jpg',
    image4: '/images/bathrooms/bathroom3.jpg',
    image5: '/images/apartments/gym3.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: 1,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,300 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2005,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '66',
    mlsId: '00066',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo4.jpg',
    image1: '/images/livingroom/lr4.jpg',
    image2: '/images/bedrooms/bedroom4.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom5.jpg',
    image5: '/images/apartments/gym4.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: 1,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,800 per/month',
    sqft: 1400,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '67',
    mlsId: '00067',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo5.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom8.jpg',
    image3: '/images/kitchen/kitchen8.jpg',
    image4: '/images/bathrooms/bathroom9.jpg',
    image5: '/images/apartments/gym6.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: 2,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '1,900 per/month',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '68',
    mlsId: '00068',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo6.jpg',
    image1: '/images/livingroom/lr8.jpg',
    image2: '/images/bedrooms/bedroom8.jpg',
    image3: '/images/kitchen/kitchen7.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym4.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: 2,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '2,900 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '69',
    mlsId: '00069',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo7.jpg',
    image1: '/images/livingroom/lr9.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen5.jpg',
    image4: '/images/bathrooms/bathroom7.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: 3,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '3,800 per/month',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '70',
    mlsId: '00070',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo8.jpg',
    image1: '/images/livingroom/lr10.jpg',
    image2: '/images/bedrooms/bedroom10.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: 3,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '3,700 per/month',
    sqft: 1700,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '71',
    mlsId: '000071',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo9.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen8.jpg',
    image4: '/images/bathrooms/bathroom12.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: 2,
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '4,200 per/month',
    sqft: 1900,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '72',
    mlsId: '00072',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo10.jpg',
    image1: '/images/livingroom/lr11.jpg',
    image2: '/images/bedrooms/bedroom10.jpg',
    image3: '/images/kitchen/kitchen5.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    rent: '4,300 per/month',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '73',
    mlsId: '00073',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo11.jpg',
    image1: '/images/livingroom/lr10.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    rent: '4,500 per/month',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '74',
    mlsId: '00074',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/condos/condo12.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '4,600 per/month',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    security: 'Secure building',
    handicap: 'Handicap accessible',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },

  //homes
  {
    id: '1',
    mlsId: '0001',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home1.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Cute 1 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '80,000',
    sqft: 1000,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2007,
    garageCapacity: 'Two Car',
    petFriendly: 'Dogs and Cats',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '2',
    mlsId: '0002',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Relators',
    verified: 'Verified',
    image: '/images/homes/home2.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Cute 1 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '85,000',
    sqft: 1100,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: 'Two Car',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '3',
    mlsId: '0003',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home3.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2 ',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '100,000',
    sqft: 1500,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '4',
    mlsId: '0004',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home4.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2 1/2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '120,000',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '5',
    mlsId: '0005',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home5.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '130,000',
    sqft: 1900,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '6',
    mlsId: '0006',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home6.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2 1/2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '135,000',
    sqft: 2100,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '7',
    mlsId: '0007',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home7.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '160,000',
    sqft: 2200,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garage: true,
    garageCapacity: '2 car',
    rating: 5,
    numReviews: 12,
  },
  {
    id: '8',
    mlsId: '0008',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home8.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '220,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 1,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '9',
    mlsId: '0009',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home9.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '240,000',
    sqft: 1900,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: 'single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '10',
    mlsId: '00010',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home10.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '260,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },

  {
    id: '11',
    mlsId: '00011',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home11.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '270,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },

  {
    id: '12',
    mlsId: '00012',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    verified: 'Verified',
    image: '/images/homes/home12.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Home',
    price: '275,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    garageCapacity: '2 car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '31',
    mlsId: '00031',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Realtors',
    image: '/images/image1.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 4 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '4 Bedroom',
    bathrooms: '3 ',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '210,000',
    sqft: 2200,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 1,
    yearBuilt: 1991,
    garageCapacity: 'Three Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '32',
    mlsId: '00032',
    realtorId: 'agent3',
    name: 'Christine Smith',
    photo: '/images/realtors/agent2.jpg',
    title: 'Realtor',
    phone: '701-555-5555',
    email: 'smithchristine@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '5 years',
    realtor: 'Dakota Relators',
    image: '/images/homes/home12.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 4 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '4 Bedroom',
    bathrooms: '3 ',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '215,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 1,
    yearBuilt: 1998,
    garageCapacity: 'Three Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },

  {
    id: '41',
    mlsId: '00041',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/image1.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 5 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '5 Bedroom',
    bathrooms: '4 ',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '910,000',
    sqft: 2700,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 1,
    yearBuilt: 2002,
    garageCapacity: 'Three Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '42',
    mlsId: '00042',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Relators',
    image: '/images/homes/home11.jpg',
    image1: '/images/livingroom/lr7.jpg',
    image2: '/images/bedrooms/bedroom9.jpg',
    image3: '/images/kitchen/kitchen6.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym5.jpg',
    description:
      'Beautiful 5 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '5 Bedroom',
    bathrooms: '4 ',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'home',
    price: '915,000',
    sqft: 2200,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 1,
    yearBuilt: 2003,
    garageCapacity: 'Three Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },

  // townhouse

  {
    id: '71',
    mlsId: '00071',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th1.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '120,000',
    sqft: 1900,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2008,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '72',
    mlsId: '00072',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th2.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse located on northside of town. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '130,000',
    sqft: 2100,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2001,
    garageCapacity: 'Single',
    garage: true,
    petFreindly: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '73',
    mlsId: '00073',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th3.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'townhouse',
    price: '140,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 1993,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '74',
    mlsId: '00074',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th4.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhose in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '150,000',
    sqft: 2600,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 1997,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '75',
    mlsId: '00075',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th5.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '160,000',
    sqft: 2200,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2011,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '76',
    mlsId: '00076',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th6.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '170,000',
    sqft: 2400,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2015,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '77',
    mlsId: '00077',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th7.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '180,000',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2015,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '78',
    mlsId: '00078',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th8.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '190,000',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2017,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
];

export default listings;
