// townhouse
const townhouse = [
  {
    id: '71',
    mlsId: '00071',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th1.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '120,000',
    sqft: 1900,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2008,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '72',
    mlsId: '00072',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th2.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse located on northside of town. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '120,000',
    sqft: 2100,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2001,
    garageCapacity: 'Single',
    garage: true,
    petFreindly: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '73',
    mlsId: '00073',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th3.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '1 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'townhouse',
    price: '120,000',
    sqft: 2300,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 1993,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '74',
    mlsId: '00074',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th4.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhose in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '130,000',
    sqft: 2600,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 1997,
    garageCapacity: 'Single',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '75',
    mlsId: '00075',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th5.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '1',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '130,000',
    sqft: 2200,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2011,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '76',
    mlsId: '00076',
    realtorId: 'agent2',
    name: 'Randy Brooks',
    photo: '/images/realtors/agent3.jpg',
    title: 'V.P, Broker-Realtor',
    phone: '701-555-5555',
    email: 'brooksrandy@gmail.com',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
    expereince: '4 years',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th6.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '2 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '130,000',
    sqft: 2400,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2015,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '77',
    mlsId: '00077',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th7.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury townhouse in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '2',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Townhouse',
    price: '130,000',
    sqft: 1600,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2015,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '78',
    mlsId: '00078',
    realtor: 'Dakota Realtors',
    image: '/images/townhouse/th8.jpg',
    image1: '/images/livingroom/lr3.jpg',
    image2: '/images/bedrooms/bedroom5.jpg',
    image3: '/images/kitchen/kitchen4.jpg',
    image4: '/images/bathrooms/bathroom8.jpg',
    image5: '/images/apartments/gym2.jpg',
    description:
      'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    rooms: '3 Bedroom',
    bathrooms: '3',
    centralAir: 'Central Air',
    washerAndDryer: 'Washer & Dryer',
    dishwasher: ' Dishwasher / Garbage disposal',
    microwave: 'Microwave',
    fitnessCenter: 'Fitness Center',
    Flooring: 'Carpet, Vinyl, Tile, Hardwood',
    propertyType: 'Condo',
    price: '130,000',
    sqft: 1800,
    location: 'Bismarck, ND, 00001',
    avalibleUnits: 2,
    yearBuilt: 2017,
    garageCapacity: 'Two Car',
    garage: true,
    rating: 5,
    numReviews: 12,
  },
];

export default townhouse;
