export const AGENT_LOGIN_REQUEST = 'AGENT_LOGIN_REQUEST';
export const AGENT_LOGIN_SUCCESS = 'AGENT_LOGIN_SUCCESS';
export const AGENT_LOGIN_FAIL = 'AGENT_LOGIN_FAIL';

export const AGENT_LOGOUT = 'AGENT_LOGOUT';

export const AGENT_REGISTER_REQUEST = 'AGENT_REGISTER_REQUEST';
export const AGENT_REGISTER_SUCCESS = 'AGENT_REGISTER_SUCCESS';
export const AGENT_REGISTER_FAIL = 'AGENT_REGISTER_FAIL';

export const AGENT_DETAILS_REQUEST = 'AGENT_DETAILS_REQUEST';
export const AGENT_DETAILS_SUCCESS = 'AGENT_DETAILS_SUCCESS';
export const AGENT_DETAILS_FAIL = 'AGENT_DETAILS_FAIL';
export const AGENT_DETAILS_RESET = 'AGENT_DETAILS_RESET';

export const AGENT_UPDATE_PROFILE_REQUEST = 'AGENT_UPDATE_PROFILE_REQUEST';
export const AGENT_UPDATE_PROFILE_SUCCESS = 'AGENT_UPDATE_PROFILE_SUCCESS';
export const AGENT_UPDATE_PROFILE_FAIL = 'AGENT_UPDATE_PROFILE_FAIL';
export const AGENT_UPDATE_PROFILE_RESET = 'AGENT_UPDATE_PROFILE_RESET';

export const AGENT_LIST_REQUEST = 'AGENT_LIST_REQUEST';
export const AGENT_LIST_SUCCESS = 'AGENT_LIST_SUCCESS';
export const AGENT_LIST_FAIL = 'AGENT_LIST_FAIL';
export const AGENT_LIST_RESET = 'AGENT_LIST_RESET';

export const AGENT_DELETE_REQUEST = 'AGENT_DELETE_REQUEST';
export const AGENT_DELETE_SUCCESS = 'AGENT_DELETE_SUCCESS';
export const AGENT_DELETE_FAIL = 'AGENT_DELETE_FAIL';

export const AGENT_UPDATE_REQUEST = 'AGENT_UPDATE_REQUEST';
export const AGENT_UPDATE_SUCCESS = 'AGENT_UPDATE_SUCCESS';
export const AGENT_UPDATE_FAIL = 'AGENT_UPDATE_FAIL';
export const AGENT_UPDATE_RESET = 'AGENT_UPDATE_RESET';
