export const CONDO_LIST_REQUEST = 'CONDO_LIST_REQUEST';
export const CONDO_LIST_SUCCESS = 'CONDO_LIST_SUCCESS';
export const CONDO_LIST_FAIL = 'CONDO_LIST_FAIL';

export const CONDO_DETAILS_REQUEST = 'CONDO_DETAILS_REQUEST';
export const CONDO_DETAILS_SUCCESS = 'CONDO_DETAILS_SUCCESS';
export const CONDO_DETAILS_FAIL = 'CONDO_DETAILS_FAIL';

export const CONDO_DELETE_REQUEST = 'CONDO_DELETE_REQUEST';
export const CONDO_DELETE_SUCCESS = 'CONDO_DELETE_SUCCESS';
export const CONDO_DELETE_FAIL = 'CONDO_DELETE_FAIL';

export const CONDO_CREATE_REQUEST = 'CONDO_CREATE_REQUEST';
export const CONDO_CREATE_SUCCESS = 'CONDO_CREATE_SUCCESS';
export const CONDO_CREATE_FAIL = 'CONDO_CREATE_FAIL';
export const CONDO_CREATE_RESET = 'CONDO_CREATE_RESET';

export const CONDO_UPDATE_REQUEST = 'CONDO_UPDATE_REQUEST';
export const CONDO_UPDATE_SUCCESS = 'CONDO_UPDATE_SUCCESS';
export const CONDO_UPDATE_FAIL = 'CONDO_UPDATE_FAIL';
export const CONDO_UPDATE_RESET = 'CONDO_UPDATE_RESET';

export const CONDO_CREATE_REVIEW_REQUEST = 'CONDO_CREATE_REVIEW_REQUEST';
export const CONDO_CREATE_REVIEW_SUCCESS = 'CONDO_CREATE_REVIEW_SUCCESS';
export const CONDO_CREATE_REVIEW_FAIL = 'CONDO_CREATE_REVIEW_FAIL';
export const CONDO_CREATE_REVIEW_RESET = 'CONDO_CREATE_REVIEW_RESET';

export const CONDO_TOP_REQUEST = 'CONDO_TOP_REQUEST';
export const CONDO_TOP_SUCCESS = 'CONDO_TOP_SUCCESS';
export const CONDO_TOP_FAIL = 'CONDO_TOP_FAIL';
