export const HOME_LIST_REQUEST = 'HOME_LIST_REQUEST';
export const HOME_LIST_SUCCESS = 'HOME_LIST_SUCCESS';
export const HOME_LIST_FAIL = 'HOME_LIST_FAIL';

export const HOME_DETAILS_REQUEST = 'HOME_DETAILS_REQUEST';
export const HOME_DETAILS_SUCCESS = 'HOME_DETAILS_SUCCESS';
export const HOME_DETAILS_FAIL = 'HOME_DETAILS_FAIL';

export const HOME_DELETE_REQUEST = 'HOME_DELETE_REQUEST';
export const HOME_DELETE_SUCCESS = 'HOME_DELETE_SUCCESS';
export const HOME_DELETE_FAIL = 'HOME_DELETE_FAIL';

export const HOME_CREATE_REQUEST = 'HOME_CREATE_REQUEST';
export const HOME_CREATE_SUCCESS = 'HOME_CREATE_SUCCESS';
export const HOME_CREATE_FAIL = 'HOME_CREATE_FAIL';
export const HOME_CREATE_RESET = 'HOME_CREATE_RESET';

export const HOME_UPDATE_REQUEST = 'HOME_UPDATE_REQUEST';
export const HOME_UPDATE_SUCCESS = 'HOME_UPDATE_SUCCESS';
export const HOME_UPDATE_FAIL = 'HOME_UPDATE_FAIL';
export const HOME_UPDATE_RESET = 'HOME_UPDATE_RESET';

export const HOME_CREATE_REVIEW_REQUEST = 'HOME_CREATE_REVIEW_REQUEST';
export const HOME_CREATE_REVIEW_SUCCESS = 'HOME_CREATE_REVIEW_SUCCESS';
export const HOME_CREATE_REVIEW_FAIL = 'HOME_CREATE_REVIEW_FAIL';
export const HOME_CREATE_REVIEW_RESET = 'HOME_CREATE_REVIEW_RESET';

export const HOME_TOP_REQUEST = 'HOME_TOP_REQUEST';
export const HOME_TOP_SUCCESS = 'HOME_TOP_SUCCESS';
export const HOME_TOP_FAIL = 'HOME_TOP_FAIL';
