# Generated by Django 4.1.2 on 2023-01-11 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('realtorId', models.CharField(blank=True, max_length=500, null=True)),
                ('realtor', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('propertyType', models.CharField(blank=True, max_length=200, null=True)),
                ('rentOrBuy', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('rooms', models.CharField(blank=True, max_length=500, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=500, null=True)),
                ('centralAir', models.CharField(blank=True, max_length=500, null=True)),
                ('washerDryer', models.CharField(blank=True, max_length=500, null=True)),
                ('microwave', models.CharField(blank=True, max_length=500, null=True)),
                ('dishwasher', models.CharField(blank=True, max_length=500, null=True)),
                ('fitnessCenter', models.CharField(blank=True, max_length=500, null=True)),
                ('flooring', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('sqft', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('securityBuilding', models.CharField(blank=True, max_length=500, null=True)),
                ('handicapAccess', models.CharField(blank=True, max_length=500, null=True)),
                ('avalibleUnits', models.CharField(blank=True, max_length=500, null=True)),
                ('garage', models.CharField(blank=True, max_length=500, null=True)),
                ('petFriendly', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
