agents = [
    {
        'id': 'agent1',
        'realtor': 'Dakota Realtors',
        'name': 'Rachel Chase',
        'image': '/images/realtors/agent1.jpg',
        'title': 'Owner- Broker',
        'phone': '701-555-5555',
        'email': 'chaserachel@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '15 years',
    },
    {
        'id': 'agent2',
        'realtor': 'Dakota Realtors',
        'name': 'Randy Brooks',
        'image': '/images/realtors/agent3.jpg',
        'title': 'V.P, Broker-Realtor',
        'phone': '701-555-5555',
        'email': 'brooksrandy@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '4 years',
        'times': '8am-11am',
        'appointments': '8am-9am, 9am-10am, 10am-11pm',
        'slot': '9:00am 10:00am',
        'slot2': '10:00am 11:00am',
        'slot3': '11:00am 12:00pm',
        'slot4': '12:00pm 1:00pm',
        'days': 'Monday-Friday',
    },
    {
        'id': 'agent3',
        'realtor': 'Dakota Realtors',
        'name': 'Christine Smith',
        'image': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'times': '11:00am-2:00pm',
        'appointments': '11am-12pm, 12pm-1pm, 1pm-2pm',
        'slot': '11:00am 12:00pm',
        'slot2': '12:00pm 1:00pm',
        'slot3': '1:00pm 2:00pm',
        'slot4': '2:00pm 3:00pm',
        'days': 'Monday-Friday',
    },
    {
        'id': 'agent4',
        'realtor': 'Dakota Realtors',
        'name': 'James Johnson',
        'image': '/images/realtors/agent4.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'johnsonjames@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '3 years',
        'times': '3:00pm-6:00pm',
        'appointments': '2pm-3pm, 3pm-4pm, 4pm-5pm, 5pm-6pm',
        'slot': '3:00pm  4:00pm',
        'slot2': '4:00pm  5:00pm',
        'slot3': '5:00pm  6:00pm',
        'days': 'Monday-Friday',
    },
]
