condos = [
    {
        'id': '63',
        'mlsId': '00063',
        'realtorId': 'agent4',
        'name': 'James Johnson',
        'photo': '/images/realtors/agent4.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'johnsonjames@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '3 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo1.jpg',
        'image1': '/images/livingroom/lr1.jpg',
        'image2': '/images/bedrooms/bedroom2.jpg',
        'image3': '/images/kitchen/kitchen1.jpg',
        'image4': '/images/bathrooms/bathroom2.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': 'Studio',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '1,500 per/month',
        'sqft': 1400,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2005,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '64',
        'mlsId': '00064',
        'realtorId': 'agent4',
        'name': 'James Johnson',
        'photo': '/images/realtors/agent4.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'johnsonjames@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '3 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo2.jpg',
        'image1': '/images/livingroom/lr2.jpg',
        'image2': '/images/bedrooms/bedroom2.jpg',
        'image3': '/images/kitchen/kitchen2.jpg',
        'image4': '/images/bathrooms/bathroom2.jpg',
        'image5': '/images/apartments/gym2.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': 'Studio',
        'bathrooms': 1,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '1,300 per/month',
        'sqft': 1100,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2005,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '65',
        'mlsId': '00065',
        'realtorId': 'agent4',
        'name': 'James Johnson',
        'photo': '/images/realtors/agent4.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'johnsonjames@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '3 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo3.jpg',
        'image1': '/images/livingroom/lr3.jpg',
        'image2': '/images/bedrooms/bedroom3.jpg',
        'image3': '/images/kitchen/kitchen3.jpg',
        'image4': '/images/bathrooms/bathroom3.jpg',
        'image5': '/images/apartments/gym3.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '1 Bedroom',
        'bathrooms': 1,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '1,300 per/month',
        'sqft': 1500,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2005,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '66',
        'mlsId': '00066',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo4.jpg',
        'image1': '/images/livingroom/lr4.jpg',
        'image2': '/images/bedrooms/bedroom4.jpg',
        'image3': '/images/kitchen/kitchen4.jpg',
        'image4': '/images/bathrooms/bathroom5.jpg',
        'image5': '/images/apartments/gym4.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '1 Bedroom',
        'bathrooms': 1,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '1,800 per/month',
        'sqft': 1400,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '67',
        'mlsId': '00067',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo5.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom8.jpg',
        'image3': '/images/kitchen/kitchen8.jpg',
        'image4': '/images/bathrooms/bathroom9.jpg',
        'image5': '/images/apartments/gym6.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': 2,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '1,900 per/month',
        'sqft': 1500,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '68',
        'mlsId': '00068',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo6.jpg',
        'image1': '/images/livingroom/lr8.jpg',
        'image2': '/images/bedrooms/bedroom8.jpg',
        'image3': '/images/kitchen/kitchen7.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym4.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': 2,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '2,900 per/month',
        'sqft': 1600,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '69',
        'mlsId': '00069',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo7.jpg',
        'image1': '/images/livingroom/lr9.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen5.jpg',
        'image4': '/images/bathrooms/bathroom7.jpg',
        'image5': '/images/apartments/gym2.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': 3,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '3,800 per/month',
        'sqft': 1600,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '70',
        'mlsId': '00070',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo8.jpg',
        'image1': '/images/livingroom/lr10.jpg',
        'image2': '/images/bedrooms/bedroom10.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': 3,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '3,700 per/month',
        'sqft': 1700,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '71',
        'mlsId': '000071',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo9.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen8.jpg',
        'image4': '/images/bathrooms/bathroom12.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': 2,
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '4,200 per/month',
        'sqft': 1900,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '72',
        'mlsId': '00072',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo10.jpg',
        'image1': '/images/livingroom/lr11.jpg',
        'image2': '/images/bedrooms/bedroom10.jpg',
        'image3': '/images/kitchen/kitchen5.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'rent': '4,300 per/month',
        'sqft': 1800,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '73',
        'mlsId': '00073',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo11.jpg',
        'image1': '/images/livingroom/lr10.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'rent': '4,500 per/month',
        'sqft': 1800,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '74',
        'mlsId': '00074',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Rent',
        'verified': 'Verified',
        'image': '/images/condos/condo12.jpg',
        'image1': '/images/livingroom/lr3.jpg',
        'image2': '/images/bedrooms/bedroom5.jpg',
        'image3': '/images/kitchen/kitchen4.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym2.jpg',
        'description':
        'Luxury condos in the heart of Downtown. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Condo',
        'price': '4,600 per/month',
        'sqft': 1800,
        'location': 'Bismarck, ND, 00001',
        'security': 'Secure building',
        'handicap': 'Handicap accessible',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
]
