homes = [
    {
        'id': '1',
        'mlsId': '0001',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home1.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Cute 1 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '1 Bedroom',
        'bathrooms': '1',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '80,000',
        'sqft': 1000,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'yearBuilt': 2007,
        'garageCapacity': 'Two Car',
        'petFriendly': 'Dogs and Cats',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '2',
        'mlsId': '0002',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Relators',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home2.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Cute 1 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '1 Bedroom',
        'bathrooms': '1',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '85,000',
        'sqft': 1100,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': 'Two Car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '3',
        'mslId': '0003',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home3.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': '2 ',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '100,000',
        'sqft': 1500,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '4',
        'mlsId': '0004',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home4.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': '2 1/2',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '120,000',
        'sqft': 1800,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '5',
        'mlsId': '0005',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home5.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': '2',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '130,000',
        'sqft': 1900,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '6',
        'mlsId': '0006',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home6.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': '2 1/2',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '135,000',
        'sqft': 2100,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '7',
        'mlsId': '0007',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home7.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '2 Bedroom',
        'bathrooms': '3',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '160,000',
        'sqft': 2200,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '8',
        'mlsId': '0008',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home8.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 2 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': '3',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '220,000',
        'sqft': 2300,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 1,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '9',
        'mlsId': '0009',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home9.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': '3',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'fitnessCenter': 'Fitness Center',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '240,000',
        'sqft': 1900,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': 'single',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '10',
        'mlsId': '00010',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home4.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': '1',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '260,000',
        'sqft': 2300,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },

    {
        'id': '11',
        'mlsId': '00011',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home11.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': '3',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '270,000',
        'sqft': 2300,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },

    {
        'id': '12',
        'mlsId': '00012',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home12.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 3 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '3 Bedroom',
        'bathrooms': '3',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'Home',
        'price': '275,000',
        'sqft': 2300,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 2,
        'garageCapacity': '2 car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '31',
        'mlsId': '00031',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home12.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 4 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '4 Bedroom',
        'bathrooms': '3 ',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '210,000',
        'sqft': 2200,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 1,
        'yearBuilt': 1991,
        'garageCapacity': 'Three Car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '32',
        'mlsId': '00032',
        'realtorId': 'agent3',
        'name': 'Christine Smith',
        'photo': '/images/realtors/agent2.jpg',
        'title': 'Realtor',
        'phone': '701-555-5555',
        'email': 'smithchristine@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '5 years',
        'realtor': 'Dakota Relators',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home8.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 4 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '4 Bedroom',
        'bathrooms': '3 ',
        'Flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '215,000',
        'sqft': 2300,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 1,
        'yearBuilt': 1998,
        'garageCapacity': 'Three Car',
        'rating': 5,
        'numReviews': 12,
    },

    {
        'id': '41',
        'mlsId': '00041',
        'realtorId': 'agent2',
        'name': 'Randy Brooks',
        'photo': '/images/realtors/agent3.jpg',
        'title': 'V.P, Broker-Realtor',
        'phone': '701-555-5555',
        'email': 'brooksrandy@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '4 years',
        'realtor': 'Dakota Realtors',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home14.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 5 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '5 Bedroom',
        'bathrooms': '4 ',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '910,000',
        'sqft': 2700,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 1,
        'yearBuilt': 2002,
        'garageCapacity': 'Three Car',
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': '42',
        'mlsId': '00042',
        'realtorId': 'agent2',
        'name': 'Randy Brooks',
        'photo': '/images/realtors/agent3.jpg',
        'title': 'V.P, Broker-Realtor',
        'phone': '701-555-5555',
        'email': 'brooksrandy@gmail.com',
        'bio': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris. Sed euismod, nunc vel tincidunt lacinia, nisl nisl aliquam mauris, quis aliquet nisl nunc vel mauris.',
        'expereince': '4 years',
        'realtor': 'Dakota Relators',
        'rentOrBuy': 'For Sale',
        'verified': 'Verified',
        'image': '/images/homes/home13.jpg',
        'image1': '/images/livingroom/lr7.jpg',
        'image2': '/images/bedrooms/bedroom9.jpg',
        'image3': '/images/kitchen/kitchen6.jpg',
        'image4': '/images/bathrooms/bathroom8.jpg',
        'image5': '/images/apartments/gym5.jpg',
        'description':
        'Beautiful 5 bedroom house with spacious backyard near local park. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        'rooms': '5 Bedroom',
        'bathrooms': '4 ',
        'centralAir': 'Central Air',
        'washerAndDryer': 'Washer & Dryer',
        'dishwasher': ' Dishwasher / Garbage disposal',
        'microwave': 'Microwave',
        'flooring': 'Carpet, Vinyl, Tile, Hardwood',
        'propertyType': 'home',
        'price': '915,000',
        'sqft': 2200,
        'location': 'Bismarck, ND, 00001',
        'avalibleUnits': 1,
        'yearBuilt': 2003,
        'garageCapacity': 'Three Car',
        'rating': 5,
        'numReviews': 12,
    },
]
